spring.application.name=produto-crud-web
server.port=8080
spring.profiles.active=dev
spring.thymeleaf.cache=false
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.build.enabled=true
